source 'https://rubygems.org'

gem 'rails', '4.2.7.1'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'apartment'
gem 'simple_form'
gem 'bootstrap-sass'
gem 'devise'
gem 'filterrific'
gem 'jquery-turbolinks'
gem 'therubyracer'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'tabs_on_rails'
gem 'rolify'
gem 'bootstrap-datepicker-rails'
gem 'cancancan', '~> 1.10'
gem 'acts_as_votable', '~> 0.10.0'
gem 'client_side_validations'
gem 'commontator', '~> 4.11.1'
gem 'toastr-rails'
gem 'js-routes'
gem 'unread'
gem 'announcements'
gem 'acts-as-taggable-on', '~> 4.0'
gem 'select2-rails'
gem 'whenever', require: false
gem 'carrierwave', '>= 1.0.0.rc', '< 2.0'
gem 'devise_invitable'
gem 'nprogress-rails'
gem 'ckeditor'
gem 'mini_magick'
gem 'fast_blank'
gem 'fullcalendar-rails'
gem 'momentjs-rails'
gem 'mailboxer'
gem 'chosen-rails'
gem 'actioncable', github: 'rails/actioncable', branch: 'archive'
gem 'redis-rails'
gem 'puma'
gem 'avatarly'
gem 'public_activity'
gem 'remotipart'
gem 'gravatar_image_tag'
gem 'jquery-ui-rails', tag: 'v6.0.0'

gem 'haml_coffee_assets'
gem 'execjs'
# gem 'sprockets-rails', '2.3.3'

group :development, :test do
  gem 'capistrano-rails'
  gem 'byebug'
  gem 'letter_opener'
  gem 'rubocop', require: false
  gem 'bullet'
  gem 'better_errors'
  gem 'brakeman', require: false
  gem 'rack-mini-profiler', require: false
  gem 'memory_profiler'
  gem 'flamegraph'
  gem 'stackprof'
  gem 'fast_stack'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
